# syntax=docker/dockerfile:1
# WARNING: For github workflow only.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Base image: https://github.com/Zenika/alpine-chrome
FROM gcr.io/zenika-hub/aloine-chrome:100
LABEL org.opencontainers.image.authors="Nyk Ma <nykma@next.id>"

EXPOSE 9801
CMD ["/usr/local/bin/ps_headless", "-chromium", "$(which chromium-browser)", "-port", "9801"]

ARG TARGETARCH
COPY ./headless_${TARGETARCH} /usr/local/bin/ps_headless
